#!/bin/bash
myDir=`dirname "$0"`
myDir=`realpath "$myDir"`
scalDir=`dirname "$myDir"`
srcDir=`dirname "$scalDir"`
rootDir=`dirname "$srcDir"`

if [ ! -f $srcDir/scal/settings/settings.go ] ; then
	STARCAL_HOST=localhost $rootDir/settings/build.py --no-build || exit $?
fi

if [[ ! -f gen.bin || gen.go -nt gen.bin ]] ; then
	echo "Compiling gen.go into gen.bin"
	GOPATH=$rootDir go build -o gen.bin gen.go || exit $?
fi
./gen.bin "$@"
